//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPhoneApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestPhoneApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS App.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.Please check network settings and try again later..
        /// </summary>
        public static string Login_LoginFailMessage {
            get {
                return ResourceManager.GetString("Login_LoginFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string Login_LoginWrongCredentials {
            get {
                return ResourceManager.GetString("Login_LoginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_PageHeader {
            get {
                return ResourceManager.GetString("Login_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login_Signin {
            get {
                return ResourceManager.GetString("Login_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_Signup {
            get {
                return ResourceManager.GetString("Login_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string ProgressBar_Loading {
            get {
                return ResourceManager.GetString("ProgressBar_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Up.
        /// </summary>
        public static string ProgressBar_SigningUpUser {
            get {
                return ResourceManager.GetString("ProgressBar_SigningUpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying User.
        /// </summary>
        public static string ProgressBar_VerifyingUser {
            get {
                return ResourceManager.GetString("ProgressBar_VerifyingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string Setting_ApplySettings {
            get {
                return ResourceManager.GetString("Setting_ApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User.
        /// </summary>
        public static string Setting_ChangeUser {
            get {
                return ResourceManager.GetString("Setting_ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tracking.
        /// </summary>
        public static string Setting_EnableTracking {
            get {
                return ResourceManager.GetString("Setting_EnableTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Settings.
        /// </summary>
        public static string Setting_InitializeSettings {
            get {
                return ResourceManager.GetString("Setting_InitializeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting_PageHeader {
            get {
                return ResourceManager.GetString("Setting_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Setting_RefreshSettings {
            get {
                return ResourceManager.GetString("Setting_RefreshSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync user settings with the server..
        /// </summary>
        public static string Setting_SyncingFailed {
            get {
                return ResourceManager.GetString("Setting_SyncingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing User Settings.
        /// </summary>
        public static string Setting_SyncingUserSettingsWithParseServer {
            get {
                return ResourceManager.GetString("Setting_SyncingUserSettingsWithParseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup_PageHeader {
            get {
                return ResourceManager.GetString("Signup_PageHeader", resourceCulture);
            }
        }
    }
}
