//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitySafe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CitySafe.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the  server. Please check network settings and try again later..
        /// </summary>
        public static string App_ConnectionError {
            get {
                return ResourceManager.GetString("App_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured. Please relaunch the application..
        /// </summary>
        public static string App_Error {
            get {
                return ResourceManager.GetString("App_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitySafe.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitySafe background location updater..
        /// </summary>
        public static string Background_Description {
            get {
                return ResourceManager.GetString("Background_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days ago.
        /// </summary>
        public static string Date_DaysAgo {
            get {
                return ResourceManager.GetString("Date_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Date_Today {
            get {
                return ResourceManager.GetString("Date_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Date_Yesterday {
            get {
                return ResourceManager.GetString("Date_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please check your network settings and try again later..
        /// </summary>
        public static string Login_LoginFailMessage {
            get {
                return ResourceManager.GetString("Login_LoginFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string Login_LoginWrongCredentials {
            get {
                return ResourceManager.GetString("Login_LoginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_PageHeader {
            get {
                return ResourceManager.GetString("Login_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up your account ....
        /// </summary>
        public static string Login_SettingUp {
            get {
                return ResourceManager.GetString("Login_SettingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login_Signin {
            get {
                return ResourceManager.GetString("Login_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_Signup {
            get {
                return ResourceManager.GetString("Login_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain your current location. Please make sure the locaion service is turned on in phone settings..
        /// </summary>
        public static string Map_CannotObtainLocation {
            get {
                return ResourceManager.GetString("Map_CannotObtainLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the location data. Please check your network settings and try again later..
        /// </summary>
        public static string Map_LoadingFailed {
            get {
                return ResourceManager.GetString("Map_LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading location data. Please wait ....
        /// </summary>
        public static string Map_LoadingLocation {
            get {
                return ResourceManager.GetString("Map_LoadingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Map_LocationHeader {
            get {
                return ResourceManager.GetString("Map_LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map_MapHeader {
            get {
                return ResourceManager.GetString("Map_MapHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my location.
        /// </summary>
        public static string Map_MyLocation {
            get {
                return ResourceManager.GetString("Map_MyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Requests.
        /// </summary>
        public static string Map_PastSOSHeader {
            get {
                return ResourceManager.GetString("Map_PastSOSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        public static string Map_SOSLocation {
            get {
                return ResourceManager.GetString("Map_SOSLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved.
        /// </summary>
        public static string Map_UnresolvedSOSHeader {
            get {
                return ResourceManager.GetString("Map_UnresolvedSOSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string ProgressBar_Loading {
            get {
                return ResourceManager.GetString("ProgressBar_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying user credentials ....
        /// </summary>
        public static string ProgressBar_VerifyingUser {
            get {
                return ResourceManager.GetString("ProgressBar_VerifyingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location update background agent is disabled by the user. Please enable it in the phone settings to allow location update in the background..
        /// </summary>
        public static string Setting_AgentDisabled {
            get {
                return ResourceManager.GetString("Setting_AgentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tracking.
        /// </summary>
        public static string Setting_EnableTracking {
            get {
                return ResourceManager.GetString("Setting_EnableTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings to the server before logging out. Please check your network settings and try again later..
        /// </summary>
        public static string Setting_FailToLogOut {
            get {
                return ResourceManager.GetString("Setting_FailToLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing settings ....
        /// </summary>
        public static string Setting_InitializeSettings {
            get {
                return ResourceManager.GetString("Setting_InitializeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last location was sent at .
        /// </summary>
        public static string Setting_LastUpdateAt {
            get {
                return ResourceManager.GetString("Setting_LastUpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Locations.
        /// </summary>
        public static string Setting_LocationUpdatePageHeader {
            get {
                return ResourceManager.GetString("Setting_LocationUpdatePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user settings ....
        /// </summary>
        public static string Setting_Loggingout {
            get {
                return ResourceManager.GetString("Setting_Loggingout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SOS.
        /// </summary>
        public static string Setting_ReceiveSOSPageHeader {
            get {
                return ResourceManager.GetString("Setting_ReceiveSOSPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync user settings with the server. Please check network settings and try again later..
        /// </summary>
        public static string Setting_SyncingFailed {
            get {
                return ResourceManager.GetString("Setting_SyncingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing user settings ....
        /// </summary>
        public static string Setting_SyncingUserSettingsWithParseServer {
            get {
                return ResourceManager.GetString("Setting_SyncingUserSettingsWithParseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send my location to the server every: .
        /// </summary>
        public static string Setting_UpdateFrequency {
            get {
                return ResourceManager.GetString("Setting_UpdateFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When people near me are in danger, notify me by:.
        /// </summary>
        public static string Setting_WhenDangerNotify {
            get {
                return ResourceManager.GetString("Setting_WhenDangerNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup_PageHeader {
            get {
                return ResourceManager.GetString("Signup_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling your last SOS request ....
        /// </summary>
        public static string SOS_CancelingRequest {
            get {
                return ResourceManager.GetString("SOS_CancelingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string SOS_CheckSurrounding {
            get {
                return ResourceManager.GetString("SOS_CheckSurrounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to past SOS requests in your area.
        /// </summary>
        public static string SOS_CheckSurroundingSubTitle {
            get {
                return ResourceManager.GetString("SOS_CheckSurroundingSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set up push notifications. Will try again at next app launch..
        /// </summary>
        public static string SOS_FailToSetUpPush {
            get {
                return ResourceManager.GetString("SOS_FailToSetUpPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Lists.
        /// </summary>
        public static string SOS_ManageList {
            get {
                return ResourceManager.GetString("SOS_ManageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not listening to SOS requests in your area.
        /// </summary>
        public static string SOS_NotificationOff {
            get {
                return ResourceManager.GetString("SOS_NotificationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listening to SOS requests in your area.
        /// </summary>
        public static string SOS_NotificationOn {
            get {
                return ResourceManager.GetString("SOS_NotificationOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        public static string SOS_PageHeader {
            get {
                return ResourceManager.GetString("SOS_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string SOS_Resolve {
            get {
                return ResourceManager.GetString("SOS_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my last SOS request.
        /// </summary>
        public static string SOS_ResolveSubTitle {
            get {
                return ResourceManager.GetString("SOS_ResolveSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SOS_SavePeople {
            get {
                return ResourceManager.GetString("SOS_SavePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the people who are in danger.
        /// </summary>
        public static string SOS_SavePeopleSubTitle {
            get {
                return ResourceManager.GetString("SOS_SavePeopleSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending your SOS request ....
        /// </summary>
        public static string SOS_SendingRequest {
            get {
                return ResourceManager.GetString("SOS_SendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SOS_SendSOS {
            get {
                return ResourceManager.GetString("SOS_SendSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS request to others.
        /// </summary>
        public static string SOS_SendSOSSubTitle {
            get {
                return ResourceManager.GetString("SOS_SendSOSSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SOS_Setting {
            get {
                return ResourceManager.GetString("SOS_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel your SOS request. Please check your network settings and try again later.
        /// </summary>
        public static string SOS_SOSCanceledFail {
            get {
                return ResourceManager.GetString("SOS_SOSCanceledFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SOS request was canceled successfully..
        /// </summary>
        public static string SOS_SOSCanceledSuccess {
            get {
                return ResourceManager.GetString("SOS_SOSCanceledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending SOS request failed. Please check your network settings and try again later..
        /// </summary>
        public static string SOS_SOSSentFail {
            get {
                return ResourceManager.GetString("SOS_SOSSentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SOS request was sent successfully..
        /// </summary>
        public static string SOS_SOSSentSuccess {
            get {
                return ResourceManager.GetString("SOS_SOSSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location tracking is turned off.
        /// </summary>
        public static string SOS_TrackingOff {
            get {
                return ResourceManager.GetString("SOS_TrackingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location tracking is turned on.
        /// </summary>
        public static string SOS_TrackingOn {
            get {
                return ResourceManager.GetString("SOS_TrackingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SOSInfo_EmailTag {
            get {
                return ResourceManager.GetString("SOSInfo_EmailTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load sender&apos;s information. Please check your network settings and try again later..
        /// </summary>
        public static string SOSInfo_LoadInfoFailed {
            get {
                return ResourceManager.GetString("SOSInfo_LoadInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading sender&apos;s info ....
        /// </summary>
        public static string SOSInfo_LoadUserInfo {
            get {
                return ResourceManager.GetString("SOSInfo_LoadUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SOSInfo_NameTag {
            get {
                return ResourceManager.GetString("SOSInfo_NameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS Request Details.
        /// </summary>
        public static string SOSInfo_PageHeader {
            get {
                return ResourceManager.GetString("SOSInfo_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string SOSInfo_PhoneTag {
            get {
                return ResourceManager.GetString("SOSInfo_PhoneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the photo. Please check network settings and try again..
        /// </summary>
        public static string SOSInfo_PhotoLoadFail {
            get {
                return ResourceManager.GetString("SOSInfo_PhotoLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Info.
        /// </summary>
        public static string SOSInfo_SenderInfo {
            get {
                return ResourceManager.GetString("SOSInfo_SenderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am in danger! Please help me!.
        /// </summary>
        public static string SOSSend_DefaultMessage {
            get {
                return ResourceManager.GetString("SOSSend_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string SOSSend_Message {
            get {
                return ResourceManager.GetString("SOSSend_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SOS Request.
        /// </summary>
        public static string SOSSend_PageHeader {
            get {
                return ResourceManager.GetString("SOSSend_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string SOSSend_Photo {
            get {
                return ResourceManager.GetString("SOSSend_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SOSSend_Settings {
            get {
                return ResourceManager.GetString("SOSSend_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share my email.
        /// </summary>
        public static string SOSSend_ShareEmail {
            get {
                return ResourceManager.GetString("SOSSend_ShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide on how much infomation you want to share in your request:.
        /// </summary>
        public static string SOSSend_ShareInfoInfo {
            get {
                return ResourceManager.GetString("SOSSend_ShareInfoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share my name.
        /// </summary>
        public static string SOSSend_ShareName {
            get {
                return ResourceManager.GetString("SOSSend_ShareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share my phone number.
        /// </summary>
        public static string SOSSend_SharePhone {
            get {
                return ResourceManager.GetString("SOSSend_SharePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share my request.
        /// </summary>
        public static string SOSSend_ShareRequest {
            get {
                return ResourceManager.GetString("SOSSend_ShareRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify the people near me and allow them to see my request..
        /// </summary>
        public static string SOSSend_ShareRequestInfo {
            get {
                return ResourceManager.GetString("SOSSend_ShareRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the user from your tracked list. Please check network settings and try again later..
        /// </summary>
        public static string TrackedSetting_FailToRemove {
            get {
                return ResourceManager.GetString("TrackedSetting_FailToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow full access to my location.
        /// </summary>
        public static string TrackedSetting_FullLocationAccess {
            get {
                return ResourceManager.GetString("TrackedSetting_FullLocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: when checked, the user who is tracking you will have access to your location data 24/7. By default, he or she will only have access to your location data when you have an unresolved SOS request..
        /// </summary>
        public static string TrackedSetting_FullLocationAccessInfo {
            get {
                return ResourceManager.GetString("TrackedSetting_FullLocationAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tracked settings ....
        /// </summary>
        public static string TrackedSetting_Loading {
            get {
                return ResourceManager.GetString("TrackedSetting_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing user from your tracked list ....
        /// </summary>
        public static string TrackedSetting_RemovingUser {
            get {
                return ResourceManager.GetString("TrackedSetting_RemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving tracked settings ....
        /// </summary>
        public static string TrackedSetting_Saving {
            get {
                return ResourceManager.GetString("TrackedSetting_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Tracker_Add {
            get {
                return ResourceManager.GetString("Tracker_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the invitation to the user with the given email. Please check your network settings and try again later..
        /// </summary>
        public static string Tracker_AddFailed {
            get {
                return ResourceManager.GetString("Tracker_AddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is added to your list successfully..
        /// </summary>
        public static string Tracker_AddSuccess {
            get {
                return ResourceManager.GetString("Tracker_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already in your list..
        /// </summary>
        public static string Tracker_AlreadyInList {
            get {
                return ResourceManager.GetString("Tracker_AlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load your private lists. Please check your network settings and try again later..
        /// </summary>
        public static string Tracker_FailToLoadList {
            get {
                return ResourceManager.GetString("Tracker_FailToLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is invalid..
        /// </summary>
        public static string Tracker_InvalidEmailMessage {
            get {
                return ResourceManager.GetString("Tracker_InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation is sent successfully..
        /// </summary>
        public static string Tracker_InvitationSuccess {
            get {
                return ResourceManager.GetString("Tracker_InvitationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading lists ....
        /// </summary>
        public static string Tracker_LoadList {
            get {
                return ResourceManager.GetString("Tracker_LoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending invitation ....
        /// </summary>
        public static string Tracker_SendingInvitation {
            get {
                return ResourceManager.GetString("Tracker_SendingInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked by.
        /// </summary>
        public static string Tracker_TrackedHeader {
            get {
                return ResourceManager.GetString("Tracker_TrackedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracker_TrackingHeader {
            get {
                return ResourceManager.GetString("Tracker_TrackingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TrackingSetting_Email {
            get {
                return ResourceManager.GetString("TrackingSetting_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email will be sent to your email address. It is recommended that you leave this feature on..
        /// </summary>
        public static string TrackingSetting_EmailInfo {
            get {
                return ResourceManager.GetString("TrackingSetting_EmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the user from your tracking list. Please check your network settings and try again later..
        /// </summary>
        public static string TrackingSetting_FailToRemove {
            get {
                return ResourceManager.GetString("TrackingSetting_FailToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tracking settings ....
        /// </summary>
        public static string TrackingSetting_Loading {
            get {
                return ResourceManager.GetString("TrackingSetting_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been denied. This user only shares location data when in danger..
        /// </summary>
        public static string TrackingSetting_LocationRequestDenied {
            get {
                return ResourceManager.GetString("TrackingSetting_LocationRequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notification.
        /// </summary>
        public static string TrackingSetting_Push {
            get {
                return ResourceManager.GetString("TrackingSetting_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because the delievery of push noticaition may be affected by network connection, user is encouraged to use it together with other notification method..
        /// </summary>
        public static string TrackingSetting_PushInfo {
            get {
                return ResourceManager.GetString("TrackingSetting_PushInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing user from your tracking list ....
        /// </summary>
        public static string TrackingSetting_RemovingUser {
            get {
                return ResourceManager.GetString("TrackingSetting_RemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check previous locations.
        /// </summary>
        public static string TrackingSetting_RequestPreviousLocation {
            get {
                return ResourceManager.GetString("TrackingSetting_RequestPreviousLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving tracking settings ....
        /// </summary>
        public static string TrackingSetting_Saving {
            get {
                return ResourceManager.GetString("TrackingSetting_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string TrackingSetting_SMS {
            get {
                return ResourceManager.GetString("TrackingSetting_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMS message will be sent to the your phone. You may be charged for receiving the message depending on your plan..
        /// </summary>
        public static string TrackingSetting_SMSInfo {
            get {
                return ResourceManager.GetString("TrackingSetting_SMSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop tracking.
        /// </summary>
        public static string TrackingSetting_StopTracking {
            get {
                return ResourceManager.GetString("TrackingSetting_StopTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the person being tracked is in danger, notify me by:.
        /// </summary>
        public static string TrackingSetting_WhenDangerNotify {
            get {
                return ResourceManager.GetString("TrackingSetting_WhenDangerNotify", resourceCulture);
            }
        }
    }
}
