//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitySafe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CitySafe.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitySafe.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.Please check network settings and try again later..
        /// </summary>
        public static string Login_LoginFailMessage {
            get {
                return ResourceManager.GetString("Login_LoginFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string Login_LoginWrongCredentials {
            get {
                return ResourceManager.GetString("Login_LoginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_PageHeader {
            get {
                return ResourceManager.GetString("Login_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login_Signin {
            get {
                return ResourceManager.GetString("Login_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Login_Signup {
            get {
                return ResourceManager.GetString("Login_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string ProgressBar_Loading {
            get {
                return ResourceManager.GetString("ProgressBar_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Up.
        /// </summary>
        public static string ProgressBar_SigningUpUser {
            get {
                return ResourceManager.GetString("ProgressBar_SigningUpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying User.
        /// </summary>
        public static string ProgressBar_VerifyingUser {
            get {
                return ResourceManager.GetString("ProgressBar_VerifyingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string Setting_ApplySettings {
            get {
                return ResourceManager.GetString("Setting_ApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User.
        /// </summary>
        public static string Setting_ChangeUser {
            get {
                return ResourceManager.GetString("Setting_ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tracking.
        /// </summary>
        public static string Setting_EnableTracking {
            get {
                return ResourceManager.GetString("Setting_EnableTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Settings.
        /// </summary>
        public static string Setting_InitializeSettings {
            get {
                return ResourceManager.GetString("Setting_InitializeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting_PageHeader {
            get {
                return ResourceManager.GetString("Setting_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Setting_RefreshSettings {
            get {
                return ResourceManager.GetString("Setting_RefreshSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync user settings with the server..
        /// </summary>
        public static string Setting_SyncingFailed {
            get {
                return ResourceManager.GetString("Setting_SyncingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing User Settings.
        /// </summary>
        public static string Setting_SyncingUserSettingsWithParseServer {
            get {
                return ResourceManager.GetString("Setting_SyncingUserSettingsWithParseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup_PageHeader {
            get {
                return ResourceManager.GetString("Signup_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage lists....
        /// </summary>
        public static string SOS_ManageList {
            get {
                return ResourceManager.GetString("SOS_ManageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        public static string SOS_PageHeader {
            get {
                return ResourceManager.GetString("SOS_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP!.
        /// </summary>
        public static string SOS_SendSOS {
            get {
                return ResourceManager.GetString("SOS_SendSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Tracker_Add {
            get {
                return ResourceManager.GetString("Tracker_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the invitation to the user with the given email..
        /// </summary>
        public static string Tracker_AddFailed {
            get {
                return ResourceManager.GetString("Tracker_AddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is added to your list successfully..
        /// </summary>
        public static string Tracker_AddSuccess {
            get {
                return ResourceManager.GetString("Tracker_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load track lists..
        /// </summary>
        public static string Tracker_FailToLoadList {
            get {
                return ResourceManager.GetString("Tracker_FailToLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Tracker_InvalidEmailMessage {
            get {
                return ResourceManager.GetString("Tracker_InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation is sent successfully..
        /// </summary>
        public static string Tracker_InvitationSuccess {
            get {
                return ResourceManager.GetString("Tracker_InvitationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading lists ....
        /// </summary>
        public static string Tracker_LoadList {
            get {
                return ResourceManager.GetString("Tracker_LoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending invitation ....
        /// </summary>
        public static string Tracker_SendingInvitation {
            get {
                return ResourceManager.GetString("Tracker_SendingInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked.
        /// </summary>
        public static string Tracker_TrackedHeader {
            get {
                return ResourceManager.GetString("Tracker_TrackedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracker_TrackingHeader {
            get {
                return ResourceManager.GetString("Tracker_TrackingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TrackingSetting_Email {
            get {
                return ResourceManager.GetString("TrackingSetting_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync user settings with the server..
        /// </summary>
        public static string TrackingSetting_FailToSync {
            get {
                return ResourceManager.GetString("TrackingSetting_FailToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tracking settings ....
        /// </summary>
        public static string TrackingSetting_Loading {
            get {
                return ResourceManager.GetString("TrackingSetting_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been denied..
        /// </summary>
        public static string TrackingSetting_LocationRequestDenied {
            get {
                return ResourceManager.GetString("TrackingSetting_LocationRequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notification.
        /// </summary>
        public static string TrackingSetting_Push {
            get {
                return ResourceManager.GetString("TrackingSetting_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing user ....
        /// </summary>
        public static string TrackingSetting_RemovingUser {
            get {
                return ResourceManager.GetString("TrackingSetting_RemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Previous Locations.
        /// </summary>
        public static string TrackingSetting_RequestPreviousLocation {
            get {
                return ResourceManager.GetString("TrackingSetting_RequestPreviousLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving tracking settings ....
        /// </summary>
        public static string TrackingSetting_Saving {
            get {
                return ResourceManager.GetString("TrackingSetting_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string TrackingSetting_SMS {
            get {
                return ResourceManager.GetString("TrackingSetting_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Tracking.
        /// </summary>
        public static string TrackingSetting_StopTracking {
            get {
                return ResourceManager.GetString("TrackingSetting_StopTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the person being tracked is in danger, notify me by:.
        /// </summary>
        public static string TrackingSetting_WhenDangerNotify {
            get {
                return ResourceManager.GetString("TrackingSetting_WhenDangerNotify", resourceCulture);
            }
        }
    }
}
